### ISSUE TITLE
Postgres password issues

### ISSUE THREAD

**Issue by damclarkd** [VirtualWolf/powerwall-to-pvoutput-uploader#1]
Sorry if this is too basic a question but I am new to Postgres and TypeScript and am having errors with this project on the 'npm run db:migrate' portion. for the longest time I could not get past an error ECONNREFUSED for port 5432 on my RPi. Got passed that by starting Postgres first. Now I continually error at a 'error: password authentication failed for user "pi"'. I set my RPi user name and password in the config.json file.
Again maybe a beginner question but, which un/pw should be in the config.json file? Also is there a problem using my RPi IP (static) instead of 'localhost' ?

Cheers and Thanks

**Comment by VirtualWolf** [comment]
No apology needed at all! :)

The default Postgres configuration under Linux is actually a bit of a pain in terms of authentication, only the `postgres` user has permission to access it. There's a few different methods to get around it, but it's pretty straightforwards to add an actual database user (with the default Postgres config, the database user also has to exist as a regular user account):
* Run `sudo -u postgres psql template1` to get into Postgres itself.
* Create a new user called `pi` to match the username from the default user: `CREATE USER pi WITH PASSWORD 'whatever-you-want';` (the Postgres password doesn't have to match the actual user password).
* Create the database: `CREATE DATABASE pvoutput;`
* Grant the `pi` user privileges to the new database: `GRANT ALL PRIVILEGES ON DATABASE pvoutput TO pi;`

Then `\q` to get out of it, update your `config.json` with the username, password, and database names you created above, and the `npm run db:migrate` should work!

> Also is there a problem using my RPi IP (static) instead of 'localhost' ?

Nah that should work fine.

**Comment by damclarkd** [comment]
> No apology needed at all! :)
> 
> The default Postgres configuration under Linux is actually a bit of a pain in terms of authentication, only the `postgres` user has permission to access it. There's a few different methods to get around it, but it's pretty straightforwards to add an actual database user (with the default Postgres config, the database user also has to exist as a regular user account):
> 
> * Run `sudo -u postgres psql template1` to get into Postgres itself.
> * Create a new user called `pi` to match the username from the default user: `CREATE USER pi WITH PASSWORD 'whatever-you-want';` (the Postgres password doesn't have to match the actual user password).
> * Create the database: `CREATE DATABASE pvoutput;`
> * Grant the `pi` user privileges to the new database: `GRANT ALL PRIVILEGES ON DATABASE pvoutput TO pi;`
> 
> Then `\q` to get out of it, update your `config.json` with the username, password, and database names you created above, and the `npm run db:migrate` should work!
> 
> > Also is there a problem using my RPi IP (static) instead of 'localhost' ?
> 
> Nah that should work fine.

Brilliant! Worked great with your instructions for Postgres. Now up and running on PVoutput with some of the info. Still sorting out the Extended data.
Thanks very much. Cheers

**Comment by VirtualWolf** [comment]
Huzzah, no worries at all! 😄

**Comment by damclarkd** [comment]
Got the Tesla PW update to 20.49.0 today and of course that broke my uploads. Delighted to come here and find your updates ready to go. Made my changes and back online. Thanks for your continued efforts!
Cheers
